version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/quirknotes
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

